### ISSUE TITLE
useWebkit=true and error: Invariant Violation: requireNativeComponent: "RNCUIWebView" was not found in the UIManager.

### ISSUE THREAD

**Issue by luatnd** [react-native-community/react-native-webview#1125]
**Bug description:**
Invariant Violation: requireNativeComponent: "RNCUIWebView" was not found in the UIManager.

This common issue tells us to link by `react-native link`, but react-native 0.61 should do it automatically.
https://github.com/react-native-community/react-native-webview#common-issues

**To Reproduce:**
react-native init new_project,
install latest react-native-webview version,
Then load WebView:
```
<WebView
            style={{ flex: 1 }}
            useWebKit={true}
/>
```
**Expected behavior:**
Auto-linking should work with react-native@0.61.x!
OR at least the error is about RNCWKWebView instead of RNCUIWebView

**Environment:**
 - OS: macOS Mojave 10.14.4
 - iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
     Xcode: 11.3/11C29 - /usr/bin/xcodebuild
 - OS version:
 - npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
 - npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by Mervsz** [comment]
I am having the same issue on react native version 0.61.5. cannot use WebView component

**Comment by luatnd** [comment]
@Mervsz As I checked `RNCUIWebView` is available in @5.x version.
So I used the 5.12.1 version with the auto-linking mechanism of react-native 0.61 
(do not run `react-native link`, do not do manual linking)

**Comment by EmilianoCervantesOmni** [comment]
Still looking for a solution.
I'm doing:
`import WebView from 'react-native-webview';`
`<WebView useWebKit={true} source={{ uri: formUrl({ clientId }) }} />`

And getting:
```
No overload matches this call.
  Overload 1 of 2, '(props: Readonly<WebViewProps>): WebView', gave the following error.
    Type '{ useWebKit: boolean; source: { uri: string; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<WebView> & Readonly<WebViewProps> & Readonly<...>'.
      Property 'useWebKit' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<WebView> & Readonly<WebViewProps> & Readonly<...>'.
  Overload 2 of 2, '(props: WebViewProps, context?: any): WebView', gave the following error.
    Type '{ useWebKit: boolean; source: { uri: string; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<WebView> & Readonly<WebViewProps> & Readonly<...>'.
      Property 'useWebKit' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<WebView> & Readonly<WebViewProps> & Readonly<...>'.ts(2769)
```

Which actually works if I do
`import { WebView } from 'react-native';`

But doing it that way is risky as `WebView` is getting pulled out from `'react-native'`

**Comment by luatnd** [comment]
still searching for solutions

**Comment by gorvinsky** [comment]
I'm having this issue too.

React Native: 0.59.9
react-native-webview: 10.10.2

**Comment by asharafshahi** [comment]
Using react-native-webview on tvOS doesn't seem to be working?  using:
`"react-native": "npm:react-native-tvos@0.63.4-0",`
`"react-native-webview": "^11.2.1"`
