### ISSUE TITLE
Cant build on Android after update to `10.1.0`

### ISSUE THREAD

**Issue by alimek** [react-native-community/react-native-webview#1408]
**Bug description:**

After upgrade from `9.4.0` to `10.1.0` I am unable to build android app.

I am getting 

```
> Task :app:compileDreamfitnessMembrSharedReleaseJavaWithJavac FAILED
XXX/react-native/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:95: error: package com.reactnativecommunity.webview does not exist
import com.reactnativecommunity.webview.RNCWebViewPackage;
                                       ^
XXX/react-native/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:181: error: cannot find symbol
      new RNCWebViewPackage()
          ^
  symbol:   class RNCWebViewPackage
  location: class PackageList
2 errors

FAILURE: Build failed with an exception.
```

Project even not syncing in Android Studio. Error `Extension not initialized yet, couldn't access compileSdkVersion.`

But `compileSdkVersion` ofc is defined.

Once downgraded to `9.4.0` everything works fine.
Cant see any changes to installation process after 10.0 breaking change, so that's why reporting this issue.

Gradlew clean doesnt help.

**Expected behavior:**

Build property on Android.

**Environment:**
 - OS: macOS
 - OS version: Catalina
 - react-native version: 0.62.2
 - react-native-webview version: 10.1.0

**Comment by henrylle** [comment]
Same error. Executing downgrade works to me too! Thanks @alimek!


Environment:

OS: Linux
OS version: Ubuntu 18.04
react-native version: 0.62.2
react-native-webview version: 10.2.0

**Comment by ahmadcore** [comment]
same error to

OS: Linux
OS version: Ubuntu 18.04
react-native version: 0.62.2
react-native-webview version: 10.2.3

**Comment by yaronlevi** [comment]
Was this bug ever resolved?
