### PR TITLE
Support React Native 0.62

### LINKED ISSUE #1280: Does not work with React Native 0.62.0
**Bug description:**
Will not yarn in a RN 0.62.0 project and gives following errors:

yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > react-native-webview@9.0.2" has incorrect peer dependency "react-native@>=0.60 <0.62".
warning " > react-native-windows@0.61.0" has incorrect peer dependency "react@16.9.0".
warning " > react-native-windows@0.61.0" has incorrect peer dependency "react-native@0.61.5".
[4/4] 🔨  Building fresh packages...
warning Error running install script for optional dependency: "/Users/martinrait/Documents/Dev/Mobi2GoStorefrontRN/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install

**To Reproduce:**
In package.json have:
"react-native": "^0.62.0"
"react": "16.11.0"
"react-native-webview": "^9.0.2"
"react-native-windows": "^0.61.0"

**Expected behavior:**
Would like a version release that works with current RN 0.62.0 (and subsequent 0.62.x releases). And a way to remove react-native-windows dependency - since that isn't required for many apps

**Environment:**
 - OS: macOS
 - OS version: 10.15.4
 - react-native version: 0.62.0
 - react-native-webview version: 9.0.2

### PR DESCRIPTION
**Pull request by jussikinnula**
Support React Native 0.62 & deprecate react-native WebView (fixed #1280)

# Summary

I created this PR to support React Native 0.62, as it doesn't anymore have WebView - so this community-driven WebView is a real must.

## Test Plan

We have tested this WebView on our React Native application, and also the example application has been updated.

### Tested with iOS

Screenshot 2020-05-06 at 18 55 45

### Tested with Android

Screenshot 2020-05-08 at 11 00 17

### Tested with Expo SDK

https://github.com/jussikinnula/react-native-webview-expo-test (see also branches)

### What's required for testing (prerequisites)?

```
yarn
yarn start:ios # Test with iOS
yarn start:android # Test with Android
```

In external projects, one can use `npm i github:jussikinnula/react-native-webview#build` or `npm i github:jussikinnula/react-native-webview#build2` (the first one doesn't support Expo, second one has that fixed as well).

### What are the steps to reproduce (after prerequisites)?

N/A

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |
| Expo iOS |    ✅     |
| Expo Android |    ✅     |
| Expo Web |    ✅     |

Note! Expo Web doesn't actually support WebView, this new implementation works similarly as it has worked earlier by displaying a box with red border.

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [X] I updated the typed files (TS and Flow)
- [X] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by jussikinnula** [comment]
I will remove "WIP" once necessary checklist steps have been taken in account. This pull request is merely added now to see work in progress by others in community, as well as possibility to test it (e.g. `npm i github:jussikinnula/react-native-webview#build`).

File: src/WebView.tsx [hunk 1]
```diff
@@ -1,5 +1,14 @@
...
+import { Text, View } from 'react-native';
+import { IOSWebViewProps, AndroidWebViewProps } from './WebViewTypes';
+
+export type WebViewProps = IOSWebViewProps & AndroidWebViewProps;
+
+const WebView: React.FunctionComponent<WebViewProps> = () => (
+  <View style={{ flex: 1 }}>
+    <Text>WebView</Text>
+  </View>
+);
```
Comment (jamonholmgren) [inline src/WebView.tsx:11]: Can you explain what you're doing here?

Comment (jussikinnula) [reply src/WebView.tsx]: I wanted to have something rendered, this is actually not needed. I'm not actually sure if we need to have "WebView" component at all in `src/`, since the native implementations will anyway get used and we have anyway separate types under root.

I removed `src/WebView.tsx` completely now.

Comment (jamonholmgren) [reply src/WebView.tsx]: Yeah, this file looks extraneous. Thanks!

Comment (jussikinnula) [reply src/WebView.tsx]: @jamonholmgren, actually the `src/WebView.tsx` is indeed needed to support Expo:

https://docs.expo.io/versions/latest/sdk/webview/

So what we basically need to do, is to create a WebView component which can be used by Expo - while the native ones that we have here are working for iOS Simulator & Android Studio emulator & etc just fine.

Comment (jussikinnula) [reply src/WebView.tsx]: Screenshot 2020-05-07 at 9 52 02

Comment (jussikinnula) [reply src/WebView.tsx]: I tested with latest Expo, and it's exactly so.

Comment (jussikinnula) [reply src/WebView.tsx]: Actually with the previous version with that "dummy" `WebView.tsx`, Expo works in Android/iPhone versions and displays "WebView" in web version.

Comment (jussikinnula) [reply src/WebView.tsx]: Here's the Expo test setup: https://github.com/jussikinnula/react-native-webview-expo-test

Comment (jussikinnula) [reply src/WebView.tsx]: The latest Expo SDK + react-native-webview 8.1.1 show empty box on web version. So basically we are not breaking anything if we re-add the dummy and remove the `<Text>WebView</Text>` part.

See that example here: https://github.com/jussikinnula/react-native-webview-expo-test/tree/current-latest-react-native-webview

And both examples with Expo work with iOS/Android. I have still yet to test Android Studio simulator and add the documentation parts, etc.

@jamonholmgren, what do you think?

Comment (jussikinnula) [reply src/WebView.tsx]: There's actually some styles defined for the empty View (that `react-native` WebView produces):

Screenshot 2020-05-08 at 9 38 53

I can match those of course if we want.

Comment (jussikinnula) [reply src/WebView.tsx:17]: The current implementation matching new implementation is now pushed, and can be tested with `npm i github:jussikinnula/react-native-webview#build` or from https://github.com/jussikinnula/react-native-webview-expo-test/tree/build2 (Expo SDK test with it).

Comment (jussikinnula) [reply src/WebView.tsx:17]: @jamonholmgren, please review the latest additions and comment if this is not clear. I added test results, and so far the only things missing greatly:

1) What version number this should be, this is a breaking change (maybe 10.0.0).
2) I have to test with real devices. I only have iOS devices in my possession, so someone might pop in and help with Android?
3) Add documentation. There's actually not that much changes from that perspective, rather than dropping legacy WebView from react-native. I can document that.

Test coverage is a bit thin in my opinion, but I guess I could have separate contribution on that end.

**Comment by jussikinnula** [comment]
For testing Android, we need to wait until https://github.com/react-native-community/cli/issues/1159 gets fixed.

**Comment by jussikinnula** [comment]
We have also tested the changed WebView on our app with real devices (both iOS and Android) with no issues.

**Comment by jussikinnula** [comment]
I would say that this patch is nearing finishing. The only questions I have:
1) How about the versioning, do we want to add it on top of this patch or done separate (there's no breaking change, even when we provide "default" WebView for Expo SDK (or other "unsupported" platforms) instead of exposing "WebView" from react-native (which was removed).
2) What do you think of documentation, should React Native 0.62 upgrade be mentioned still in "breaking changes" list?
3) Do we want to wait until https://github.com/react-native-community/cli/issues/1159 is released before merging this? The only issue is with this project's Android example, which needs it in order to work. The fix is already merged, but not yet released.

**Comment by jussikinnula** [comment]
@kaiguo, could you check why the Windows CI is failing? I guess the used Windows React Native doesn't work with React Native 0.62?

**Comment by jussikinnula** [comment]
> @kaiguo, could you check why the Windows CI is failing? I guess the used Windows React Native doesn't work with React Native 0.62?

```##[error]     9>d:\a\react-native-webview\react-native-webview\node_modules\react-native-windows\reactcommon\build\x64\release\reactcommon\react-native-patched\reactcommon\yoga\yoga\bitutils.h(48): error C2220: warning treated as error - no 'object' file generated (compiling source file D:\a\react-native-webview\react-native-webview\node_modules\react-native-windows\ReactCommon\build\x64\Release\ReactCommon\react-native-patched\ReactCommon\yoga\yoga\Utils.cpp) [D:\a\react-native-webview\react-native-webview\node_modules\react-native-windows\ReactCommon\ReactCommon.vcxproj]```

**Comment by kaiguo** [comment]
> @kaiguo Kai Guo FTE, could you check why the Windows CI is failing? I guess the used Windows React Native doesn't work with React Native 0.62?

@jussikinnula yeah there were some breaking changes on react-native-windows side, I'll open a PR to upgrade Windows to 62.

**Comment by kaiguo** [comment]
@jussikinnula I opened a PR against your branch to upgrade windows to 62, https://github.com/jussikinnula/react-native-webview/pull/1, feel free to merge that in if everything looks good to you : )

**Comment by jussikinnula** [comment]
> @jussikinnula I opened a PR against your branch to upgrade windows to 62, [jussikinnula#1](https://github.com/jussikinnula/react-native-webview/pull/1), feel free to merge that in if everything looks good to you : )

Thanks, it looked good :)

**Comment by arryanggaputra** [comment]
@jussikinnula  how to install your MR to my apps?

**Comment by jussikinnula** [comment]
> @jussikinnula how to install your MR to my apps?

We are using currently `npm i github:jussikinnula/react-native-webview#build` version, it doesn't have the newest changes I rebased a moment ago. I would consider it proof-of-concept, so you can test your software with it but you should wait until this PR gets merged and use official build instead.

**Comment by jamonholmgren** [comment]
@jussikinnula (nice Finnish name there btw) would you mind resolving conflicts on this? I’ll get it merged next release.
