### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

### ISSUE THREAD

**Issue by chenweigh** [react-native-community/react-native-webview#1471]
### Environment
```
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-webview": "^10.3.1"
```

### Run command
`yarn android`

### Problem Description
```
> Task :react-native-webview:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
114 actionable tasks: 111 executed, 3 up-to-date
注: /Users/chen/ReactNative/CxyParent1/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
注: /Users/chen/ReactNative/CxyParent1/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/chen/ReactNative/CxyParent1/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
注: /Users/chen/ReactNative/CxyParent1/node_modules/react-native-view-shot/android/src/main/java/fr/greweb/reactnativeviewshot/RNViewShotModule.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
/Users/chen/ReactNative/CxyParent1/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewModule.java:276: 错误: 找不到符号
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                                                    ^
  符号:   变量 Q
  位置: 类 VERSION_CODES
注: /Users/chen/ReactNative/CxyParent1/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/chen/ReactNative/CxyParent1/node_modules/react-native-webview/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-webview:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
```

How to solve it.

**Comment by exmlcxjv** [comment]
same problem .....

**Comment by tomhall** [comment]
Working in v9.4.0, stops working at v10.0.0.

**Comment by muhamed91** [comment]
Also the same Problem

**Comment by foneazmi** [comment]
same problem, i use latest ver,

**Comment by yasir-syed** [comment]
any update on this ? is it working ?

**Comment by chenweigh** [comment]
try this version and it run smoothly 
`yarn add react-native-webview@8.0.2`
